[package]
name = "svgparser"
# When updating version, also modify html_root_url in the lib.rs
version = "0.4.1"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["svg", "parser", "tokenizer"]
categories = ["parsing"]
license = "MPL-2.0"
description = "Simple, streaming, zero-allocation SVG parser."
repository = "https://github.com/RazrFalcon/libsvgparser"
documentation = "https://docs.rs/svgparser/"
readme = "README.md"

[badges]
travis-ci = { repository = "RazrFalcon/libsvgparser" }

[dependencies]
phf = "=0.7.21"

[dev-dependencies]
bencher = "0.1"

[[bench]]
name = "parser"
harness = false
