[package]
name = "svgparser"
version = "0.3.1"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["svg", "parser", "tokenizer"]
license = "MPL-2.0"
description = "Simple, streaming, zero-allocation SVG parser."
repository = "https://github.com/RazrFalcon/libsvgparser"
documentation = "https://docs.rs/svgparser/"
readme = "README.md"

[dependencies]
phf = "=0.7.21"
