[package]
name = "codegen"
version = "0.1.0"
authors = ["RazrFalcon <razrfalcon@gmail.com>"]
license = "MPL-2.0"

[dependencies]
phf = "=0.7.21"
phf_codegen = "=0.7.21"
itertools = "0.6.0"
derive-error = "0.0.3"
